// <auto-generated />
using diplom2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace diplom2.Migrations
{
    [DbContext(typeof(WebServicesContext))]
    [Migration("20171215112217_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("diplom2.Events", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Day");

                    b.Property<string>("Description");

                    b.Property<int>("Month");

                    b.Property<string>("Name");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("diplom2.TableOfStatements", b =>
                {
                    b.Property<string>("AccountNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ApplicationDate");

                    b.Property<string>("TypeOfStatement");

                    b.Property<bool>("Verification");

                    b.HasKey("AccountNumber");

                    b.ToTable("TableOfStatements");
                });

            modelBuilder.Entity("diplom2.TimeTables", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Group");

                    b.Property<string>("LessonName");

                    b.Property<string>("LessonTeacher");

                    b.Property<string>("Room");

                    b.Property<int>("SerialNumberLectures");

                    b.Property<int>("Week");

                    b.HasKey("Id");

                    b.ToTable("TimeTables");
                });

            modelBuilder.Entity("diplom2.UserTable", b =>
                {
                    b.Property<string>("AccountNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Dob");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("GroupName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.HasKey("AccountNumber");

                    b.ToTable("UserTable");
                });
#pragma warning restore 612, 618
        }
    }
}
